// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// MCMC
Rcpp::List MCMC(arma::mat const& Y, arma::mat const& sites, arma::mat const& spatial_covariates, arma::mat const& knots, arma::mat const& dsk, arma::mat const& dss, int const& niter, int const& nburn, int const& nthin, int const& trace, arma::vec const& gev_vary, arma::mat const& gev_init, double const& alpha_init, double const& tau_init, double const& A_init, double const& B_init, double const& sills_init, double const& ranges_init, arma::mat const& constant_gev_prior, arma::vec const& alpha_prior, arma::vec const& tau_prior, double const& beta_variance_prior, arma::mat const& sill_prior, arma::mat const& range_prior, arma::vec const& gev_random_walk, arma::vec const& range_random_walk, double const& tau_random_walk, double const& alpha_random_walk, double const& A_random_walk, double const& B_random_walk, bool const& quiet, std::string const& latent_processes_correlation_type, arma::mat const& nas);
RcppExport SEXP hkevp_MCMC(SEXP YSEXP, SEXP sitesSEXP, SEXP spatial_covariatesSEXP, SEXP knotsSEXP, SEXP dskSEXP, SEXP dssSEXP, SEXP niterSEXP, SEXP nburnSEXP, SEXP nthinSEXP, SEXP traceSEXP, SEXP gev_varySEXP, SEXP gev_initSEXP, SEXP alpha_initSEXP, SEXP tau_initSEXP, SEXP A_initSEXP, SEXP B_initSEXP, SEXP sills_initSEXP, SEXP ranges_initSEXP, SEXP constant_gev_priorSEXP, SEXP alpha_priorSEXP, SEXP tau_priorSEXP, SEXP beta_variance_priorSEXP, SEXP sill_priorSEXP, SEXP range_priorSEXP, SEXP gev_random_walkSEXP, SEXP range_random_walkSEXP, SEXP tau_random_walkSEXP, SEXP alpha_random_walkSEXP, SEXP A_random_walkSEXP, SEXP B_random_walkSEXP, SEXP quietSEXP, SEXP latent_processes_correlation_typeSEXP, SEXP nasSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat const& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type sites(sitesSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type spatial_covariates(spatial_covariatesSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type knots(knotsSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type dsk(dskSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type dss(dssSEXP);
    Rcpp::traits::input_parameter< int const& >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< int const& >::type nburn(nburnSEXP);
    Rcpp::traits::input_parameter< int const& >::type nthin(nthinSEXP);
    Rcpp::traits::input_parameter< int const& >::type trace(traceSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type gev_vary(gev_varySEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type gev_init(gev_initSEXP);
    Rcpp::traits::input_parameter< double const& >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< double const& >::type tau_init(tau_initSEXP);
    Rcpp::traits::input_parameter< double const& >::type A_init(A_initSEXP);
    Rcpp::traits::input_parameter< double const& >::type B_init(B_initSEXP);
    Rcpp::traits::input_parameter< double const& >::type sills_init(sills_initSEXP);
    Rcpp::traits::input_parameter< double const& >::type ranges_init(ranges_initSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type constant_gev_prior(constant_gev_priorSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type alpha_prior(alpha_priorSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type tau_prior(tau_priorSEXP);
    Rcpp::traits::input_parameter< double const& >::type beta_variance_prior(beta_variance_priorSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type sill_prior(sill_priorSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type range_prior(range_priorSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type gev_random_walk(gev_random_walkSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type range_random_walk(range_random_walkSEXP);
    Rcpp::traits::input_parameter< double const& >::type tau_random_walk(tau_random_walkSEXP);
    Rcpp::traits::input_parameter< double const& >::type alpha_random_walk(alpha_random_walkSEXP);
    Rcpp::traits::input_parameter< double const& >::type A_random_walk(A_random_walkSEXP);
    Rcpp::traits::input_parameter< double const& >::type B_random_walk(B_random_walkSEXP);
    Rcpp::traits::input_parameter< bool const& >::type quiet(quietSEXP);
    Rcpp::traits::input_parameter< std::string const& >::type latent_processes_correlation_type(latent_processes_correlation_typeSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type nas(nasSEXP);
    __result = Rcpp::wrap(MCMC(Y, sites, spatial_covariates, knots, dsk, dss, niter, nburn, nthin, trace, gev_vary, gev_init, alpha_init, tau_init, A_init, B_init, sills_init, ranges_init, constant_gev_prior, alpha_prior, tau_prior, beta_variance_prior, sill_prior, range_prior, gev_random_walk, range_random_walk, tau_random_walk, alpha_random_walk, A_random_walk, B_random_walk, quiet, latent_processes_correlation_type, nas));
    return __result;
END_RCPP
}
